language: objective-c
osx_image: xcode8.2
rvm:
  - 2.3.1
cache:
  directories:
  - Carthage
install:
- gem install xcpretty
- bin/bootstrap-if-needed
script:
- xcodebuild -project SpechtLite.xcodeproj -scheme "SpechtLite" build CODE_SIGN_IDENTITY=""
  CODE_SIGNING_REQUIRED=NO | xcpretty
before_deploy:
- openssl aes-256-cbc -K $encrypted_f333a4d93d89_key -iv $encrypted_f333a4d93d89_iv -in secret.tar.enc -out cert/secret.tar -d
- tar xvf cert/secret.tar
- security create-keychain -p mysecretpassword build.keychain
- security default-keychain -s build.keychain
- security unlock-keychain -p mysecretpassword build.keychain
- security set-keychain-settings -t 3600 -u build.keychain
- security import cert/MacDistribution.p12 -k build.keychain -T /usr/bin/codesign -P ""
- security import cert/MacDeveloper.p12 -k build.keychain -T /usr/bin/codesign -P ""
- "security set-key-partition-list -S apple-tool:,apple: -s -k mysecretpassword build.keychain"
- "[ -f $(git rev-parse --git-dir)/shallow ] && git fetch --unshallow"
- gem install github-markup redcarpet --no-ri --no-rdoc
- gem install gym
- fastlane gym -s SpechtLite --disable_xcpretty
- ditto -c -k --sequesterRsrc --keepParent SpechtLite.app SpechtLite.zip
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: IGPLdiy+AuIA3fjZA2d7BM3qiu0cvIGPhRaU9gnPLjXLKggB2vRFfZUHjB3TSvVJ1yX5Pf5xO5iCmJvlfDF2QHf0rTQKwsGBX+Q7iloLtaw+mYYpCwnpVR8IVDmEtDvw59p/YOsBhh490XckCOs1ihA9vZPGmuGz+Ap1vFMQNadRnO1hfBgxGJ9Jg6QptM+O5QP83DgEaZcJbin7mZKftWFAQf5vJgtRZHEY2NTfoejLj8P6hesPEeO5UDfwQYl0z4nrDlC1jK5Tyh6d9IRYxyKtuzl8kydk//KncsMmX2quWUl81urRrt8NEGh/niHzY1FGfvjm3W0vIhK3ELoDolZlKHpB02fTfkdleyOozQSGN+1pKT2aHuo1HkU8J9YTY2tKhu0qIocHwdTvDRS9gWbhmbrBg9MC3tmfKNpp8japH1I8W2Rhk1wQPKNLwpk/XUcB73/NV84uGTTVLNiV+AEFtxRzNf4hx/fQT8FvkjV5zSyQhPuQXhjv0Zqpx+CA/SIQZbrPwqmPyEA183ZTyyLD0Uwm+3pix8TPU4z7+kOhh/ydXoRxkRxqHX98eXwSp5e8Y1+Xuv7udLsQ89PqjtKYMpjRMYBkZxvQSL02etJCy+EgknHsxwbbfaQ6IMXQeDtxk97WKBgy7O461Bb5kswNuDPztICkVX3H849MFSc=
  file: SpechtLite.zip
  on:
    repo: zhuhaow/SpechtLite
    tags: true
after_deploy:
- bin/publish_appcast
env:
  global:
    secure: g0sfjKq7v5PZopMdYkCY+8fStbfSXiaHLW8M8VaaB0XqP57akQaEhPbusV03tLDw99STvI+0Nt8y3x+4LXB+bRGJlfPLiRjZu0h5iLQSUcB34WZzPHsgIs3Cy3ZIz1HYp71jRjmvUonmtFMFkCeBBh7elzPEsqZBLPafnayH7ws0QrKGdhDLho9Am0akBk49c1MbBG5kzdPbUMuRf2AgYpUopIJ/ZXQs6/RGGNWOK4yYT9rUtmcQgzt62V4Y5KEgt4jIW2pEEFi3GocGgAhskfbiGE4YUzKEFaQhVNjbPcc4GVQPlykeED77M14ndQBPJx4TTfDip7wAtYnBh3oiup8UXnNAqP/tmnJDkrCroDj00QS2GUU5GUr9aH4tLijYrCynbtTCiF02WUGnZSdkGN+3Rf6n04BNKqL0E879Pk+KKBLF/xXG7T9GQ4s5vHOZ0dyQz68VCWPpMNPlBZQ93QGk+KIS0Zjut8JlI12Stsv6yeoYdqN//oPNAgg16vouKsRHCytH02IvR278ELXrEAbEaWihyoDsBYNsCk6kuI0o0PArqogxYInrpkaUSZa7bmoCiScEBziJvg3N7MTMHeWvT9pz4uJElFuMHEGp5SPdN6JgSk+RkKnIaY0AMVuTn+5S5gLFkaj8wH2ahvwMKIPE6sG1eujfrBg0tRosq9U=
